version: '2.1'

services:
  egghead-twelve-factor:
    image: egghead-twelve-factor
    build: .
    env_file:
      - .env
    environment:
      NODE_ENV: development
    ports:
      - 3000:8080
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 index.js